### PR TITLE
Add support for ctrl-r insert-mode pasting

### PR DESCRIPTION
**Pull request by jasonccox**

### CODE REVIEW

**Comment by jasonccox** [comment]
@wind0204 Would you be willing to try this out and make sure it's all working as you'd expect? I've never actually used `ctrl-r` before and don't feel 100% qualified to claim it works.

**Comment by wind0204** [comment]
> @wind0204 Would you be willing to try this out and make sure it's all working as you'd expect? I've never actually used `ctrl-r` before and don't feel 100% qualified to claim it works.

I'm happy to help @jasonccox. This code did work for me but I found out that there are a few more features in vim similar to the feature of `i_CTRL-R` when I took a look at https://github.com/kana/vim-fakeclip/blob/59858dabdb55787d7f047c4ab26b45f11ebb533b/plugin/fakeclip.vim#L238 yesterday which are `i_CTRL-R_CTRL-O`, `i_CTRL-R_CTRL-P` and `i_CTRL-R_CTRL-R`. --I think it would be nice to also support these cases just in case someone would copy-paste a lot of code. These features are aware of code indentation.

**Comment by jasonccox** [comment]
> I found out that there are a few more features in vim similar to the feature of `i_CTRL-R` when I took a look at https://github.com/kana/vim-fakeclip/blob/59858dabdb55787d7f047c4ab26b45f11ebb533b/plugin/fakeclip.vim#L238 yesterday which are `i_CTRL-R_CTRL-O`, `i_CTRL-R_CTRL-P` and `i_CTRL-R_CTRL-R`. --I think it would be nice to also support these cases just in case someone would copy-paste a lot of code. These features are aware of code indentation.

I included those in the change as well, actually. Can you take one more look and see if they're working as well?

**Comment by wind0204** [comment]
I thought they were not supported but they do work fine, the problem was in yanking part, whenever I yank the register is filled with a short string 'wl' while the wayland clipboard is correctly getting filled with the selected part of the buffer, I can paste the selected part out of vim, but when I paste using "+ register the buffer gets the short string 'wl'.

I'll do more investigation on this. I have done some investigation but so far I've found an unrelated bug: calling `has` function with `'+clipboard'` as an argument instead of `'clipboard'`
```
diff --git a/plugin/wayland_clipboard.vim b/plugin/wayland_clipboard.vim
index 0ca2c4b..6c10093 100644
--- a/plugin/wayland_clipboard.vim
+++ b/plugin/wayland_clipboard.vim
@@ -22,14 +22,14 @@ endif
 
 " Yanking {{{
 
-" On Vim builds without '+clipboard', the '+' register doesn't work for
+" On Vim builds without 'clipboard', the '+' register doesn't work for
 " yanking. My solution is to map '"+' to '"w' and send the 'w' register to the
 " Wayland clipboard as well.
 "
 " This variable controls whether '"+' gets mapped to '"w'. It's on by default
-" if the '+clipboard' feature isn't available, but the user can turn it off
+" if the 'clipboard' feature isn't available, but the user can turn it off
 " always if desired.
-let s:plus_to_w = !has('+clipboard') && !exists('g:wayland_clipboard_no_plus_to_w')
+let s:plus_to_w = !has('clipboard') && !exists('g:wayland_clipboard_no_plus_to_w')
 
 " remap '"+' to '"w' -- this will only apply to yanking since '"+p' and '"+P'
 " are also remapped below
```

**Comment by wind0204** [comment]
Well I didn't know that the string written in "+ is not important at all when I posted https://github.com/jasonccox/vim-wayland-clipboard/pull/3#issuecomment-828920536 disregard my theory in this post please.

it turns out that this code does work fine in every function, it was just that this code doesn't help with the mappings in my vim rc `file:`
```
nnoremap <Leader>p "+p
nnoremap <Leader>P "+P
```

**Comment by wind0204** [comment]
If I replace the unremappable mappings in my vim rc file with the normal version it works fine. I think a final touch of supporting `.noremap` mappings mapped by end users would be nice which somehow supported by https://github.com/kana/vim-fakeclip

I've just found a new bug in the tests: if you press `+` a little late after delay after pressing `CTRL-R` vim just writes what is really written in "+ register bypassing the mapping done by this plugin which somehow doesn't occur with https://github.com/kana/vim-fakeclip

I'm sorry for commenting too many times.

**Comment by wind0204** [comment]
I've found out that the bug that just writes what is written in "+ when user has waited too long after pressing `CTRL-R` can be fixed by attaching `&` right at the end of the left-hand side argument for the mapping of CTRL-R pasting. like below:
```
for cr in ['<C-R>', '<C-R><C-R>', '<C-R><C-O>', '<C-R><C-P>']
    execute "map! " . cr . "+& <C-O>:<C-U>" . prepaste . "<CR>" . cr . "\""
endfor
```

Unfortunately however I haven't found any documentation about this magical ampersand.

**Comment by jasonccox** [comment]
>  I've found an unrelated bug: calling has function with '+clipboard' as an argument instead of 'clipboard'

You're right -- good catch! I've fixed that on `master`.

> I think a final touch of supporting .noremap mappings mapped by end users would be nice which somehow supported by https://github.com/kana/vim-fakeclip

> I've just found a new bug in the tests: if you press + a little late after pressing CTRL-R vim just writes what is really written in "+ register instead, bypassing the mapping done by the plugin, which somehow doesn't occur with https://github.com/kana/vim-fakeclip

I agree that these would be nice, but I'm honestly not that great with vimscript and don't know how I'd handle them. More importantly, though, this plugin is really just meant to be a simple workaround for the basic use cases. I'm glad that vim-fakeclip seems to support some more advanced use cases, and I won't be offended if you choose to keep using it instead.

> Changing imap to map! to also support pasting in command mode would be very nice.

I tried this and unfortunately the mappings don't work as-is for command mode since they rely on entering command mode to mess with the registers. I may explore this more in the future, but for now I'll just leave that support out.

I think I'll add some notes to the readme about what exactly is supported and how to avoid issues with the mappings so that other users know what to expect. Thanks for your help testing and for diving into several of these issues!

**Comment by wind0204** [comment]
>

> I've found out that the bug that just writes what is written in "+ when user has waited too long after pressing `CTRL-R` can be fixed by attaching `&` right at the end of the left-hand side argument for the mapping of CTRL-R pasting. like below:
> 
> ```
> for cr in ['<C-R>', '<C-R><C-R>', '<C-R><C-O>', '<C-R><C-P>']
>     execute "map! " . cr . "+& <C-O>:<C-U>" . prepaste . "<CR>" . cr . "\""
> endfor
> ```
> 
> Unfortunately however I haven't found any documentation about this magical ampersand.
I was wrong about this, the ampersand prevents this mapping from working even when all the keys in a key sequence was pressed within 'timeoutlen', vim just waits for the last character '&'. Please disregard another wrong theory of mine. I'm sorry for writing wrong and confusing test results.

**Comment by wind0204** [comment]
> If I replace the unremappable mappings in my vim rc file with the normal version it works fine. I think a final touch of supporting `.noremap` mappings mapped by end users would be nice which somehow supported by https://github.com/kana/vim-fakeclip
> 
> I've just found a new bug in the tests: if you press `+` a little late after pressing `CTRL-R` vim just writes what is really written in "+ register instead, bypassing the mapping done by the plugin, which somehow doesn't occur with https://github.com/kana/vim-fakeclip
> 
> Changing `imap` to `map!` to also support pasting in command mode would be very nice.

I was wrong! all over my investigation, https://github.com/kana/vim-fakeclip doesn't support them either. both unremappable version mappings and waiting more than 'timeoutlen' milliseconds between key presses in the key sequences.

**Comment by jasonccox** [comment]
No worries! Thanks for all your help with this!

**Pull request merged**
